### ISSUE TITLE
Split maven_servers

### ISSUE THREAD

**Issue by arkadiuszmigalaperform** [robertstettner/drone-mvn-auth#4]
Current usage enable us to put _maven_servers_ section as 
```[{"id": "release","username":"foo","password":"bar"}]```
but what if company policy provides just password (e.g. NEXUS_PASSWORD) as secret?

As this configuration is not working with secrets:
```
servers:
      - id: release
        username: ${NEXUS_USERNAME}
        password: ${NEXUS_PASSWORD}
      - id: snapshot
        username: ${NEXUS_USERNAME}
        password: ${NEXUS_PASSWORD}
```

Then there's no possibility to do it. 

IMO, it's good to fix servers username and password to be able to pass secret into it.
